name: nock
description: HTTP requests mocking library for dart and flutter. Test your application in isolation.
version: 1.2.1
homepage: https://github.com/cah4a/dart_nock

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: 1.21.4
  collection: ^1.16.0

dev_dependencies:
  http: ^0.13.5
  pedantic: ^1.11.1
